apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    move2kube.konveyor.io/service: spring-boot-2-hello-world
  name: spring-boot-2-hello-world
spec:
  ports:
    - name: port-8080
      port: 8080
      targetPort: 8080
  selector:
    move2kube.konveyor.io/service: spring-boot-2-hello-world
  type: ClusterIP
status:
  loadBalancer: {}
