
---
apiVersion: v1
data:
    .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJpbmRleC5kb2NrZXIuaW8iOiB7CgkJCSJhdXRoIjogImEyOXlhV1pwWTJZNlZHVnpkREV5TXpRaiIKCQl9Cgl9Cn0=
kind: Secret
metadata:
    creationTimestamp: null
    name: index-docker-io-imagepullsecret
type: kubernetes.io/dockerconfigjson

...
